#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Aplmint"
email = "prism2048@outlook.com"

[git]
private-commits = "empty()"
# fetch = "upstream"
# push = "origin"

[ui]
default-command = ["log", "--limit", "7"]

[merge-tools.vimdiff]
merge-args = [
  "-f",
  "-d",
  "$output",
  "-M",
  "$left",
  "$base",
  "$right",
  "-c",
  "wincmd J",
  "-c",
  "set modifiable",
  "-c",
  "set write"
]
program = "nvim"
merge-tool-edits-conflict-markers = true
