hwdec=nvdec
vo=gpu
gpu-api=auto
save-position-on-quit

# subtitle
sub-auto=all
sub-font="Maple Mono NF CN"
sub-bold=yes
sub-ass-force-margins=yes

# playlist
loop-playlist=inf

# highest quality
profile=high-quality

# yt-dlp
ytdl-raw-options=cookies-from-browser=firefox #write-subs=,sub-langs=danmaku,convert-subs=ass,

# Optimized shaders for higher-end GPU: Mode A (HQ)
glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
